tryber/sd-07-trybeer

back-end/models/connection.js, back-end/package-lock.json, front-end/package-lock.json, front-end/package.json, package-lock.json
- Configuração  banco de dados MySQL - backend model
=> [Grupo 8] - Configuração inicial

back-end/controllers/loginController.js, back-end/index.js, back-end/models/connection.js, back-end/models/loginModel.js, back-end/routes/loginRoute.js, back-end/services/loginService.js
Configuracao de back-end/login/token
=> Main group 15 back login

back-end/controllers/LoginController.js, back-end/controllers/index.js, back-end/index.js, back-end/middlewares/validateTokenMiddleware.js, back-end/models/LoginModel.js, back-end/models/connection.js, back-end/models/index.js, back-end/package-lock.json, back-end/package.json, back-end/routes/Login.js, back-end/routes/index.js, back-end/services/LoginService.js, back-end/services/LoginValidations.js, back-end/services/index.js
Adicionada a rota do /login utilizando o método post, feita a validação se o usuário passa o email e se a senha possui mais de 6 dígitos. 
É feita a validação se o usuário existe no banco, e então é gerado um token.
Criado o middleware para verificar se o token passado é valido.
Caso todas as validações retornem ok o retorno é o seguinte json { token, email, name, role }
rota para requisição do token: http://localhost:3000/login (método post)
Usuario valido para teste:
{
"email":"user@test.com",
"password":"test123"
}
=> [GROUP-8][Back-End] Gerando token e realizando as validações.

README.md, front-end/package-lock.json, front-end/package.json, front-end/src/App.js, front-end/src/actions/index.js, front-end/src/components/Routes.jsx, front-end/src/components/index.js, front-end/src/index.js, front-end/src/pages/Login/Login.jsx, front-end/src/pages/index.js, front-end/src/reducers/clientInfo.js, front-end/src/reducers/index.js, front-end/src/services/api.js, front-end/src/services/localStorage.js, front-end/src/store/index.js, package-lock.json, package.json
##################################
O que foi feito:
=> [GROUP 10] - Login Pt. 1

front-end/src/Pages/Login/index.js, front-end/src/Pages/Register/index.js
Alterando alguns termos que o teste procura no momento de validar nas páginas de Login e Registro
=> Correção para passar no teste

back-end/controllers/UserController.js, back-end/index.js, back-end/models/UserModel.js, back-end/services/UserService.js
#91 #requisito 6 - cadastro  de pedidos na tabela sales
=> requisito 6- backend-feito

.gitignore, cypress/integration/req01-login.spec.js, front-end/src/components/Login.js, front-end/src/components/Register.js, front-end/src/context/Provider.js, front-end/src/pages/Register.js, front-end/src/routes.js
=> Login req1 botao para registro

front-end/src/Pages/ClientProfile/index.js, front-end/src/servicesAPI/api.js, front-end/src/util/changeLocalStorage.js
Falta a o sidebar para passar nos testes.
=> Requisito 4 - Profile Client

back-end/controllers/userController.js, back-end/models/UserModel.js, back-end/routes/index.js, back-end/routes/loginRoute.js, back-end/routes/registerRoute.js, back-end/services/UserService.js, back-end/services/validations/userValidation.js, package-lock.json
=> Main group 5 bk req2

back-end/src/controllers/loginController.js, back-end/src/middlewares/loginMiddleware.js, back-end/src/models/usersModel.js, back-end/src/routes/loginRoute.js, back-end/src/utils/auth.js
arquivos alterados para comparação
=> alterações apenas para conferir

front-end/src/pages/Login.js, front-end/src/store/index.js
começando requisito 1 frontend
=> frontend 1

front-end/src/pages/Login.js, front-end/src/pages/Register.js, front-end/src/services/User.js
=> 13 group sd 07 trybeer project frontend 2

back-end/README.md, back-end/controllers/SaleController.js, back-end/controllers/index.js, back-end/index.js, back-end/models/ProductModel.js, back-end/models/SaleModel.js, back-end/models/UserModel.js, back-end/routes/Sale.js, back-end/routes/index.js, back-end/services/SaleService.js, back-end/services/index.js, back-end/services/validations/SaleValidations.js
Validação dos dados informados pelo usuário com os dados que constam no banco de dados e realizada inserção do pedido.
=> [Group 8][Back-End] Requisito 6

back-end/routes.js, back-end/src/controllers/index.js, back-end/src/controllers/productController.js, back-end/src/models/Product.js, back-end/src/services/productService.js
Rota de Get All products:
response:
[{
"imagem": "pathnameimage",
"nome": "cerveja",
"preco": 20,
} ... ]
=> Get-produto-Req5-Task1-main-group-2

back-end/README.md, back-end/controllers/SaleController.js, back-end/models/SaleModel.js, back-end/routes/Sale.js, back-end/services/LoginService.js, back-end/services/SaleService.js
Criada a rota localhost:3001/sales/:saleid
Criado o metodo get na rota /sales para retorno das compras realizadas
Criado o metodo get na rota /sales/:saleid para o retorno dos detalhes da compra.
Modificada a rota /sale para /sales
Foi adicionado no README do back-end como utilizar as novas rotas.
=> [Group 8][Back-End] Requisitos 7 e 8

back-end/package-lock.json, front-end/package-lock.json, front-end/src/components/EmailInput.jsx, front-end/src/components/hamburguerMenu/HamburgerButtom.jsx, front-end/src/components/sideBar/SideBar.jsx, front-end/src/routes/ClientRouts.jsx, front-end/src/views/Profile.jsx
Reverts tryber/sd-07-trybeer#242
=> Revert "Main group 5 ft profile"

back-end/controllers/index.js, back-end/controllers/saleController.js, back-end/helpers/index.js, back-end/helpers/validationsHelper.js, back-end/index.js, back-end/models/index.js, back-end/models/saleModels.js, back-end/routes/index.js, back-end/routes/saleRoutes.js, back-end/services/index.js, back-end/services/saleServices.js, back-end/services/userServices.js
Adicionamos o valitationsHelper.js e refatoramos alguns pontos da API.
=> [Main group 10] [backend] - Refactoring

back-end/controllers/productController.js, back-end/models/ProductModel.js, back-end/routes/index.js, back-end/routes/productsRouter.js, back-end/services/ProductService.js
- Criar funcionalidade para retornar todos os produtos na rota `/products`
=> [GRUPO 5] - Requisito 05

front-end/src/actions/index.js, front-end/src/components/Address.js, front-end/src/components/Card.js, front-end/src/pages/Checkout.js, front-end/src/pages/Products.js, front-end/src/reducers/index.js, front-end/src/reducers/order.js, front-end/src/services/Order.js
=> 13 group sd 07 trybeer project frontend 6

back-end/helper/AuthValidation.js, back-end/services/ProductService.js, back-end/services/UserService.js
- ajustes de mensagens do UserService
=> [GRUPO 5] Requisito 04 - ajustes

front-end/src/components/Address.js, front-end/src/components/AdminSidebar.js, front-end/src/pages/AdminOrderDetails.js, front-end/src/pages/AdminOrders.js, front-end/src/pages/AdminProfile.js
=> 13 group sd 07 trybeer project requisito 9

back-end/controllers/orderController.js, back-end/models/OrderModel.js, back-end/routes/index.js, back-end/routes/orderRoute.js, back-end/services/OrderService.js, back-end/services/orderService.js
=> [GRUPO 5] Requisito 12 Backend

front-end/src/views/AdminOrders.jsx, front-end/src/views/AdminProfile.jsx
=> [GRUPO 5] Requisito 10 - frontend

front-end/src/components/Beers.js, front-end/src/components/Checkout.js, front-end/src/components/CheckoutBody.js, front-end/src/components/CheckoutCard.js, front-end/src/pages/Checkout.js, front-end/src/routes.js
=> Client-Checkout-Req5-task1-main-group-2

front-end/src/context/Provider.js, front-end/src/pages/profileAdmin/index.js, front-end/src/pages/profileClient/index.js, front-end/src/pages/register/index.js
=> main group 7 - req 2 e 4 fix

back-end/router/salesRoutes.js, front-end/src/pages/OrderDetailsAdmin/index.jsx, front-end/src/pages/OrderDetailsUser/index.jsx, front-end/src/pages/index.js, front-end/src/routes/index.jsx, front-end/src/services/index.js
Finalizei o requisito 8.
O que falta para o req. 12:
-Fazer o fetch no botão de mudar status do pedido
=> Main group 11 req 8 e 12 front

front-end/src/components/Beers.js, front-end/src/components/CheckoutBody.js, front-end/src/components/CheckoutCard.js
=> Client checkout req6 task3 main group 2

front-end/src/actions/index.js, front-end/src/components/AdminOrderCard.js, front-end/src/pages/AdminOrderDetails.js, front-end/src/pages/AdminOrders.js, front-end/src/pages/OrderDetails.js, front-end/src/reducers/adminOrder.js, front-end/src/reducers/adminOrders.js, front-end/src/services/apiServices.js, front-end/src/services/order.js
=> 13 group sd 07 trybeer project requisito 11 12

back-end/products/services/index.js
=> Fix Checks

front-end/src/components/Card.js, front-end/src/pages/Checkout.js, front-end/src/pages/Products.js
=> resolvendo os bos
